from library.PatternCount import pattern_count
from library.PatternCount import pattern_positions_in_genome

def test1():
    text = 'TAATACCGAGAGACTTTCTTAATACCTCATCGGTCGAGATAATACCCGGCCGCACCTAATACCGGTGATTAATACCCCATAATACCGATAATACCTGATCGCATTAGGTAATACCTAATACCTAATACCCGCTAATACCCGGTAATACCATAATACCATAATACCCATAATACCTTAATACCGTAATACCAGTAATACCTAATACCGCTAATACCGTAATACCGGTAATACCGTAATACCAGTAATACCCTAATACCGTAATACCGACTGGCATAATACCTTAATACCGCCGGATCAATCGATTAATACCCGTTATGACTAATACCTACATAATACCACGCAGTAATACCTGGTTAATACCCTAATACCTTAATACCGTAATACCATTAATACCCTGTAATACCTTGTTAATACCTAATACCGGAGTTATAATACCTAACCGGCATAATACCTTTCGGTGATCTAGAATTAATTAATACCCTACTAATACCTAAACCTATTAATACCGGCTGTGTTAATACCAATAATACCGCTAATACCATAATACCTAATACCTAATACCGTAATACCGCGACTCGTAATACCCGTAATACCTAATACCTAATACCTAATACCTAATACCGTTTCTCATAATACCTAATACCATAATACCTAATACCGCATAATACCTAATACCATTGTTAATACCTAATACCTTAATACCATAATACCAACTAATACCGAAGCTAATACCTCCATGTAATACCGCTAATACCTAGCGCAAAGGTCCCTAATACCACTAATACCAATATAATACCTTGTAACTAATACCCGAAGCATAATACCTTCGCCTAATACCTAATACCCCCGTAATACCGTTAATACCCACAATAATACCCTAATACCAGTAATACCTACGCTGCCCATAATACCGCTAATACCGGTTAATACCACTTTAATACCGTAATACCAGTAATACCTAATACCGGATAATACCGATAATACCGTAATACCAACAGGGATAATACCGTGAA'
    pattern = 'TAATACCTA'
    print(pattern_count(pattern, text))

def test2():
    print(pattern_positions_in_genome('ATAT', 'GATATATGCATATACTT'))    

def test3():
    pattern = 'CTTGATCAT'
    with open('dataset/VibrioCholerae.txt') as file:
        content = file.readlines()
    genome = [line.strip() for line in content][0]

    print(' '.join(str(p) for p in pattern_positions_in_genome(pattern, genome)))    

test1()
test2()
test3()